### ISSUE TITLE
Comando "require('faker-br')" não encontra o faker-br

### ISSUE THREAD

**Issue by HeraldoJunior** [tamnil/faker-br#11]
![image](https://user-images.githubusercontent.com/30849655/123961859-2fc23080-d987-11eb-83ef-9681baf51cc0.png)

![image](https://user-images.githubusercontent.com/30849655/123962013-5b451b00-d987-11eb-8ddf-c248bf9a4db3.png)

**Comment by tamnil** [comment]
Por que voce colocou @types/faker-br  no npm install? 
Onde  voce viu essa instrução?
