### ISSUE TITLE
Could not find a declaration file for module 'faker-br'. '(pasta do projeto) faker-br/index.js' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by marinabeenedetti** [tamnil/faker-br#26]
Oi!
Estou instalando a sua versão do faker para um projeto aonde preciso gerar cnpj, em cypress!
Na hora da instalação dá tudo certo e cria os arquivo, dentro do package.json está incluindo também.

Porém quando importar o arquivo, tem dado erro: 

Could not find a declaration file for module 'faker-br'. 'c:/Users/marin/projects/cypress-direto-do-ponto/node_modules/faker-br/index.js' implicitly has an 'any' type.

Tentei fazer a importação de duas formas:
const faker = require('faker-br');

ou através do import
import { faker } from 'faker-br'
e as duas dá o mesmo erro

**Comment by tamnil** [comment]
voce esta usando typescript?

**Comment by marinabeenedetti** [comment]
> voce esta usando typescript?

não, é javascript mesmo!

**Comment by marinabeenedetti** [comment]
https://github.com/marinabeenedetti/cypress-direto-do-ponto/blob/main/cypress/e2e/finance.cy.js 

coloquei em um projeto que eu fiz de estudo, compartilhei ele aqui caso você queria conferir alguma configuração. Eu só instalei e tentei importar mesmo, pode ser que faltou algo? ahah

**Comment by tamnil** [comment]
Eu testei seu projeto aqui e o cypress nao apresentou erro com faker

**Comment by tamnil** [comment]
essa mensagem eh so um Info do eslint, deve dar pra usar normalemente.

**Comment by tamnil** [comment]
Voce pode desabilitar o linter para typescript nessa linha tbm, ele ainda nao foi portado para TS nessa versao

**Comment by marinabeenedetti** [comment]
Realmente a mensagem de alerta não era o problema, hoje deu certo kkk obrigada pela ajuda! funcionou perfeitamente agora, não sei porque ahah
